# Generated by Django 4.2 on 2025-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://previews.123rf.com/images/igoun/igoun1905/igoun190500141/123440040-spoon-fork-icon-restaurant-canteen-cutlery-or-foodcourt-illustrationt-as-a-simple-vector-sign.jpg', max_length=500),
        ),
    ]
