# Generated by Django 4.2 on 2025-11-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_item_item_desc_alter_item_item_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user_name', 'item_price'], name='food_item_user_na_360e37_idx'),
        ),
    ]
